

---

## 🧱 Creating NumPy Arrays – Simplified Guide

### 1. **How to Create NumPy Arrays**

You can create arrays by converting Python lists or using NumPy’s built-in functions:

* `np.zeros()` → Array filled with 0s
* `np.ones()` → Array filled with 1s
* `np.full()` → Array filled with a custom value
* `np.eye()` → Identity matrix (used in linear algebra)
* `np.arange()` → Array with a range of values
* `np.linspace()` → Array with evenly spaced values

These methods save time and avoid manual loops.

---

### 2. **Checking Array Properties**

Every NumPy array has useful info:

* `shape` → Rows and columns
* `size` → Total number of elements
* `ndim` → Number of dimensions (1D, 2D, etc.)
* `dtype` → Data type of elements

Knowing these helps you write better and faster code.

---

### 3. **Changing Data Types**

You can set or convert array data types like `int32`, `float64`, etc.
This helps control memory use and precision, especially with large datasets.

---

### 4. **Reshaping & Flattening**

* **Reshape**: Change the structure (e.g., 1D to 2D)
* **Flatten**: Turn multi-dimensional arrays into a 1D array

Useful in machine learning and data preprocessing.

---

### ✅ Key Takeaways

* NumPy arrays are faster than lists because they use fixed types.
* Built-in creation methods make code cleaner and quicker.
* Understanding shapes and types boosts performance.
* Reshape and flatten help manage data structure easily.

---



import numpy as np
arr=np.zeros((2,2))
arr

In [5]:
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [12]:
arr = np.full((2,5),5)
arr

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [15]:
arr = np.linspace(0,1,7)
arr

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [28]:
arr= np.array([[1,2,3],[6,7,8]])
arr.size

6

In [29]:
arr.shape


(2, 3)

In [30]:
arr.dtype


dtype('int64')

In [31]:
arr.ndim

2

In [32]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype="float")


In [34]:
myarr.dtype

dtype('float64')

In [42]:
new=myarr.astype(np.int32)
new

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)

In [43]:
new.dtype

dtype('int32')

In [44]:
new.shape

(4, 3)

In [45]:
new.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int32)

In [48]:
print(new.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
