
---

## 🔍 A Deeper Dive into Key NumPy Concepts

### 📡 Broadcasting in NumPy

**Broadcasting** is a powerful feature in NumPy that enables operations on arrays with different shapes—without needing explicit loops or reshaping.

**How It Works:**

* When you perform an operation between arrays of differing shapes, NumPy automatically "broadcasts" the smaller array to match the dimensions of the larger one.
* For example, adding a scalar to an array applies the scalar to every element — effortlessly and efficiently.

**Why It’s Important:**

* **Memory Efficient**: Avoids creating duplicate data during operations.
* **Faster Computation**: Optimized under-the-hood for high performance.
* **Widely Used**: Essential for matrix operations, data transformation, and deep learning workflows.

---

### 🔗 Integrating NumPy with Pandas

**Pandas** builds on top of NumPy to offer a more structured and flexible approach to data analysis. While NumPy handles raw numerical data, Pandas simplifies tasks like data cleaning, labeling, and manipulation.

**Why They Work So Well Together:**

* **Under the Hood**: Pandas uses NumPy arrays for efficient data storage and computation.
* **Vectorized Performance**: Enables fast operations over entire columns or rows.
* **Advanced Indexing**: Makes handling missing data and labels seamless.

**When to Use What:**

* 👉 Use **NumPy** for high-speed mathematical and matrix operations.
* 👉 Use **Pandas** when working with structured/tabular data like CSVs, Excel files, or SQL outputs.

---

### ⚙️ Optimizing NumPy Arrays for Better Performance

NumPy already offers great speed, but with a few tweaks, you can push performance even further—especially when working with large datasets.

**Optimization Tips:**

* **Choose the Right Data Type**: Use smaller data types (like `float32` instead of `float64`) to reduce memory usage.
* **Prefer Views Over Copies**: Views reference the original array without copying data, improving both speed and memory efficiency.
* **Use Built-in Functions**: Avoid writing loops—NumPy’s functions like `np.sum()`, `np.dot()`, and `np.mean()` are highly optimized.
* **Track Memory Usage**: Use `.nbytes` to check how much memory an array consumes and adjust accordingly.

---

### 📌 Key Takeaways

* **Broadcasting** simplifies array operations and removes the need for manual looping.
* **Pandas** harnesses NumPy’s capabilities while offering intuitive tools for structured data analysis.
* **Performance Optimization** can drastically improve speed and memory usage, especially in data-heavy applications.

---



In [2]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype="float")

In [3]:
flat = arr.flatten()
flat

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [4]:
flat[0:5]

array([1., 2., 3., 4., 5.])

In [5]:
flat[::3]


array([ 1.,  4.,  7., 10.])

In [6]:
flat[5:]







array([ 6.,  7.,  8.,  9., 10., 11., 12.])

In [7]:
b = flat[3:7]
print(b)



[4. 5. 6. 7.]


In [8]:
b[0] = 1
b

array([1., 5., 6., 7.])

In [9]:
flat

array([ 1.,  2.,  3.,  1.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [11]:
b = flat[4:9].copy()
b

array([5., 6., 7., 8., 9.])

In [12]:
b[0] = 1
b

array([1., 6., 7., 8., 9.])

In [13]:
print(flat)

[ 1.  2.  3.  1.  5.  6.  7.  8.  9. 10. 11. 12.]


In [14]:
flat[flat<4]


array([1., 2., 3., 1.])

In [15]:
idx = [1,5,8]
flat[idx]

array([2., 6., 9.])

***Create a 3×3 array filled with random numbers and print its shape.***

In [18]:
arr3 = np.array([[2,35,7],[2,23,5],[23,567,8]])
arr3.shape

(3, 3)

***Convert an array of floats [1.1, 2.2, 3.3] into integers[1.1, 2.2, 3.3]***

In [24]:
flt_arr = np.array([1.1, 2.2, 3.3])
int_arr = flt_arr.astype(np.int32)
print(flt_arr.dtype,"data type is converted data type : ",int_arr.dtype)

float64 data type is converted data type :  int32


***Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].***

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6])
idx = [1,3,5]
print("Even number from the array are: ",arr[idx])

Even number from the array are:  [2 4 6]


***Reshape a 1D array of size 9 into a 3×3 matrix.
Use boolean masking to filter numbers greater than 50 in an array.***

In [26]:
arr = np.array([2,35,7,233,23,54,23,567,8])
arr.shape

(9,)

In [27]:
reshape_arr=arr.reshape((3,3))
reshape_arr.shape

(3, 3)

In [28]:
print("Number Greater then 50: ",arr[arr>50])

Number Greater then 50:  [233  54 567]
