

---

### 🔢 **1. Understanding Axes in NumPy**

* Each **dimension** in a NumPy array = **axis**.
* Axes start from 0.

| Array Type | Axes                                            |
| ---------- | ----------------------------------------------- |
| 1D         | axis 0                                          |
| 2D         | axis 0 = rows, axis 1 = columns                 |
| 3D         | axis 0 = depth, axis 1 = rows, axis 2 = columns |

🧮 **Sum Examples** (for 2D array):

```python
np.sum(arr, axis=0)  # Down each column
np.sum(arr, axis=1)  # Across each row
```

---

### 🧭 **2. Indexing in Multidimensional Arrays**

* Access element in 2D: `arr[row, column]`
* **Example:** `arr[1, 2]` → 2nd row, 3rd column

✂️ **Slicing Example:**

```python
arr[0:2, 1:3]  # First 2 rows, last 2 columns
```

---

### 📦 **3. Indexing in 3D Arrays**

* Format: `arr[depth, row, column]`
* **Shape Example:** `(2, 2, 3)` → 2 sheets, 2 rows, 3 columns

🧾 **Examples:**

```python
arr3D[0, 1, 2]    # Output: 6
arr3D[:, 0, :]    # First row from each sheet
```

---

### 🛠 **4. Selecting Data Along Axes**

* `arr[:, 0]` → All rows of column 0 (2D)
* `arr3D[:, 0, :]` → First row from each 3D sheet

---

### ✏️ **5. Changing Data Along an Axis**

* Replace a full column:

```python
arr[:, 1] = 0  # Sets entire column 1 to 0
```

---

### 📌 **6. Summary**

* **Axis 0** → Rows (vertical)
* **Axis 1** → Columns (horizontal)
* **2D indexing** → `arr[row, col]`
* **3D indexing** → `arr[depth, row, col]`
* Use **slicing** for subarrays.
* Use `axis` in functions like `sum()` to operate efficiently without loops.




In [1]:
import numpy as np
 
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
 
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))     

[12 15 18]
[ 6 15 24]


In [5]:
print(arr[0:3,1:3])

[[2 3]
 [5 6]
 [8 9]]


In [6]:
arr3d = np.array([
    [[1,2,3],
     [4,5,6]], #dept1
    
    [[7,8,9],
     [10,11,12]#depth2
    ]


])

In [10]:
print(arr3d[0,1,1])

5


In [11]:
arr3d[1,1,2]

np.int64(12)

In [13]:
print(arr3d[:,0,:])

[[1 2 3]
 [7 8 9]]


In [16]:
arr3d[:,0,:] = 0
print(arr3d)

[[[ 0  0  0]
  [ 4  5  6]]

 [[ 0  0  0]
  [10 11 12]]]


In [17]:
arr3d[:,:,2]

array([[ 0,  6],
       [ 0, 12]])