In [1]:
import numpy as np
arr = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

In [2]:
np.max(arr)

np.int64(50)

In [3]:
np.min(arr)

np.int64(10)

In [4]:
np.mean(arr)


np.float64(30.0)

In [5]:
np.median(arr)

np.float64(30.0)

In [6]:
np.argmin(arr)

np.int64(0)

In [7]:
np.argmax(arr)

np.int64(14)

In [11]:
np.std(arr)

np.float64(10.801234497346433)

In [12]:
np.var(arr)

np.float64(116.66666666666667)

In [13]:
np.prod(arr)

np.int64(1012934162288508928)

In [14]:
np.sum(arr)

np.int64(450)

In [16]:
np.percentile(arr,23)

np.float64(21.1)

In [17]:
np.unique(arr)

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [18]:
np.diff(arr)

array([[10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10]])

In [19]:
np.log(arr)


array([[2.30258509, 2.99573227, 3.40119738],
       [2.7080502 , 3.21887582, 3.55534806],
       [2.99573227, 3.40119738, 3.68887945],
       [3.21887582, 3.55534806, 3.80666249],
       [3.40119738, 3.68887945, 3.91202301]])

In [20]:
np.exp(arr)

array([[2.20264658e+04, 4.85165195e+08, 1.06864746e+13],
       [3.26901737e+06, 7.20048993e+10, 1.58601345e+15],
       [4.85165195e+08, 1.06864746e+13, 2.35385267e+17],
       [7.20048993e+10, 1.58601345e+15, 3.49342711e+19],
       [1.06864746e+13, 2.35385267e+17, 5.18470553e+21]])

In [21]:
np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
np.cumsum(arr)

array([ 10,  30,  60,  75, 100, 135, 155, 185, 225, 250, 285, 330, 360,
       400, 450])

In [ ]:
np.corrcoef(arr1, arr2)